server:
  port: 9003
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.49.2:30036/BC32-GreenCommute
    username: root
    password: password
  application:
    name: ROUTE-SERVICE



