name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ['jobs-microservice', 'microservice-location', 'routes-microservice', 'Skills-microservice']
        
    defaults:
      run:
        working-directory: Backend/${{ matrix.dir }}
        
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Java JDK
      uses: actions/setup-java@v3.9.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build jar files
      run: mvn clean install -DskipTests

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        # username: ${{github.actor}}
        username: Mohammed-Sameeruddin
        password: ${{secrets.TOKEN}}
        
    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/$username/${{matrix.dir}}:${{ github.run_number }}
        docker push ghcr.io/$username/${{matrix.dir }}:${{ github.run_number }}
        
        
