name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ['Backend/jobs-microservice', 'Backend/microservice-location', 'Backend/routes-microservice', 'Backend/skills-microservice']
        
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
        
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Java JDK
      uses: actions/setup-java@v3.9.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.TOKEN}}
        
    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/${{secrets.OWNER}}/${{matrix.dir}}:${{ github.run_number }}
        docker push ghcr.io/${{secrets.OWNER}}/${{matrix.dir}}:${{ github.run_number }}
        
        
